### ISSUE TITLE
Easy way to get modal props

### ISSUE THREAD

**Issue by GustavoBonfimS** [colorfy-software/react-native-modalfy#113]
Just to document and help anyone who finds it interesting. In my projects I have been using this method to import the properties of the modal. I think it's a little simpler than the default.

Instead of use
```tsx
type Props = ModalComponentProp<
  ModalStackParams,
  void,
  'PaymentMethodSelectModal'
>;
```

We can use
```tsx
type Props = ModalProps<'PaymentMethodSelectModal'>;
```

Or directly in the component
```tsx
function PaymentMethodSelectModal({
  modal: { getParam, closeModal },
}: ModalProps<'PaymentMethodSelectModal'>) { }
```

With this implementation
```ts
interface ModalStackParams {
  PaymentMethodSelectModal: {
    foo: string;
  }
}

export const stack = createModalStack(modalConfig, {
  backdropOpacity: 0.3,
  position: 'bottom',
});


export type ModalProps<
  T extends keyof ModalStackParams = keyof ModalStackParams,
> = ModalComponentProp<ModalStackParams, void, T>;
```

I have saved this in my Stack settings file and use it when I need it.

I hope it helps. ❤️ 
This issue can be closed

**Comment by CharlesMangwa** [comment]
thanks a lot for taking the time to write this @GustavoBonfimS! actually #114 might even make the whole typescript situation even easier! 😼

**Comment by GustavoBonfimS** [comment]
Nice work,  thanks! ❤️
