### ISSUE TITLE
Sending `onAnimatedValueUpdate` with no listeners registered.

### ISSUE THREAD

**Issue by emilnili** [colorfy-software/react-native-modalfy#124]
Seems we get these errors now with modals when updated to new react native.

`"react-native": "0.72.4",`
`"react-native-gesture-handler": "~2.12.0",`

The error occurs when the modal is closed, and it seems the animation does not work properly either.
The options for the modal that causes this error looks like this:

`transitionOptions: (animatedValue) => ({
      opacity: animatedValue.interpolate({
        inputRange: [0, 1, 2],
        outputRange: [0, 1, 0.9],
      }),
      transform: [
        {
          translateX: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: [-width / 2, 0, 25],
          }),
        },
        {
          rotate: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: ["-19deg", "0deg", "19deg"],            
          }),
        },
        {
          scale: animatedValue.interpolate({
            inputRange: [0, 1, 2],
            outputRange: [0.8, 1, 0.8],
          }),
        },
      ],
    }),
    animateInConfig: {
      easing: Easing.bezier(0.42, -0.03, 0.27, 0.95),
      duration: 400,
    },
    animateOutConfig: {
      easing: Easing.bezier(0.42, -0.03, 0.27, 0.95),
      duration: 300,
    },
  };`

Removing this transitionOptions will cause the error to disappear. But the modal will not have any nice animation...

**Comment by ermamud** [comment]
I am seeing similar issue while using the exact same code they have in the example folder

**Comment by CharlesMangwa** [comment]
hey @emilnili! could you provide a repro on [snack](https://snack.expo.dev/) please? that would make it easier for debugging

**Comment by ermamud** [comment]
you can use the same snack i shared with you in the other issue, i can see the warnings here:

https://snack.expo.dev/@ermamud/modalfy_error_test

**Comment by stalteri** [comment]
same issue
"react-native": "0.73.0",
"react-native-gesture-handler": "2.14.0",
"react-native-modalfy": "3.5.2"

![image](https://github.com/colorfy-software/react-native-modalfy/assets/48121568/9523c600-6d64-4fda-b4be-03b1d5783797)

**Comment by hlspablo** [comment]
Same here.
Context: RN 0.73, Expo 50, React Router v3
