### ISSUE TITLE
[iOS] open modal when screen has options presentation: "modal"

### ISSUE THREAD

**Issue by vietanhdtd** [colorfy-software/react-native-modalfy#125]
I have encountered a problem when using a modal on a screen that has the option `presentation: "modal"`. The modal always shows up behind it.

To address this issue, I came up with a workaround that involves wrapping the screen content with `ModalProvider`. However, this approach results in opening two modals, and I am unable to close the modal on a screen with `presentation: "modal"`.

If anyone has a better solution for this case, please share it with me. Thank you.

<img src="https://github.com/colorfy-software/react-native-modalfy/assets/35613053/498ba8b3-b107-41e2-88fb-c32e3ccd879f" width="30%" height="30%">

**Comment by CharlesMangwa** [comment]
hey @vietanhdtd! could you provide a repro on [snack](https://snack.expo.dev) please?

**Comment by vietanhdtd** [comment]
@CharlesMangwa thank you for responding. Here's snake of the problem i mention above:

https://snack.expo.dev/@vietanhdtd/modalfy-screen-presentation-modal

![CleanShot 2023-09-25 at 11 54 51](https://github.com/colorfy-software/react-native-modalfy/assets/35613053/8aea1eb8-037d-4295-b43a-7a467081c617)


And only happen on iOS.

**Comment by CharlesMangwa** [comment]
hey @vietanhdtd! sorry for the delayed response. unfortunately, i do not have an idea how to address your issue effectively. i'd need to spend some more time trying things before i can potentially release a patch. apologies for the inconvenience.

**Comment by CharlesMangwa** [comment]
hey @vietanhdtd! sorry for the delayed response. unfortunately, i do not have an idea how to address your issue effectively. i'd need to spend some more time trying things before i can potentially release a patch. apologies for the inconvenience.

**Comment by fobos531** [comment]
Hello @CharlesMangwa, I opened a PR #149 which fixes this
