### ISSUE TITLE
How to configure the option to close automatically (e.g. after 3000 ms) and not to close when clicking on the background?

### ISSUE THREAD

**Issue by clin211** [colorfy-software/react-native-modalfy#133]
How to configure the option to close automatically (e.g. after 3000 ms) and not to close when clicking on the background?

**Comment by Forest-211** [comment]
I want to set the modal not to close when clicking on the background when calling openModal, and also how to set it to close automatically when calling openModal (e.g.: automatically close after 3000ms)

**Comment by CharlesMangwa** [comment]
hey @clin211! thank you for your patience. in case you haven't figure out how to make this happen yet:

1. you can prevent the backdrop/back button from closing the modal by setting the modal option [`backBehavior: 'none'`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions#backbehavior).
2. a regular `useEffect` inside the modal component that's being opened should do the trick:
```js
// ./modals/AlertModal.tsx

// ...

  useEffect(() => {
    const timeout = setTimeout(closeAllModals, 3000)
    return () => clearTimeout(timeout)
  }, [closeAllModals])

// ...
```
