### ISSUE TITLE
Responsive Background

### ISSUE THREAD

**Issue by ivanatomicc** [colorfy-software/react-native-modalfy#137]
Hey!
Is it possible to somehow keep the UI responsive in the background while the modal is open? 
Thanks in advance!

**Comment by CharlesMangwa** [comment]
hey @ivanatomicc! thanks for your patience with this delayed response. the behavior you're asking for is not provided by modalfy and is not planned anytime soon. however, if you want to open a pull request to that effect, i'll be more than happy to support you with some directions if need be.
