### ISSUE TITLE
Is it possible to pass a parameter which is a callback function to the modal?

### ISSUE THREAD

**Issue by kokosky93** [colorfy-software/react-native-modalfy#138]
Hi,

I am struggling how to do the following things

I need to notify my react native component which opened a modal when the modal is closed. How can I do this?

Is it possible to pass parameters from a modal component to a component which opened the modal?

Anyone would know how can I do this?

**Comment by CharlesMangwa** [comment]
hey @kokosky93! thanks for your patience with this reply. what you're asking for is possible via a mix of [`modal.addListener`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modalcomponentprop#addlistener) & [`modal.params`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modalcomponentprop#addlistener).

i've modified the demo snack to make a functional example of what you're trying to achieve: https://snack.expo.dev/safxFTYCR7x1FVsncrkmt. you can focus on `./components/IntroButton.tsx#L16` & `./components/IntroModal.tsx#L73` and follow the threads from there.

hope this helps!
