### ISSUE TITLE
Cannot select text or move cursor of TextInput inside a modal when keyboard is visible

### ISSUE THREAD

**Issue by EduFrazao** [colorfy-software/react-native-modalfy#143]
Hi. Thanks for this very nice library!
I've noted a weird behavior trying to select text, or move the cursor of a TextInput that is displayed inside a Modal.
It simple not work on Android when the keyboard is visible.

I've tryed with different Android devices, like Motorola MotoG (Android 11), Xiaomi Poco Xe (Android 12), HoneyWell (Android 8).
TextInputs outside modal areas works fine.

Note: I can't replicate this problem on Android Emulator.

Bellow, a video with the issue.

[Screencast from 2024-04-03 18-58-58.webm](https://github.com/colorfy-software/react-native-modalfy/assets/994671/0681404f-d5db-4113-aced-0652d4e265bf)

Any tips will be very mutch appreciated :).

**Comment by CharlesMangwa** [comment]
closing for now as no repro was provided. feel free to reopen whenever you'll have one!
