### ISSUE TITLE
disable BackHandler for android

### ISSUE THREAD

**Issue by forchello** [colorfy-software/react-native-modalfy#148]
Sometimes we need to lock the back button on android so that we don't miss business logic. Is there any way to solve this problem?

**Comment by CharlesMangwa** [comment]
hi @forchello, you can do so via modality's [`backBehavior`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions#backbehavior) & react native's [BackHandler](https://reactnative.dev/docs/backhandler) if need be.
