### ISSUE TITLE
Modal Animation Transition Configs Seemingly Not Working

### ISSUE THREAD

**Issue by Kaboudouo** [colorfy-software/react-native-modalfy#155]
I'm trying to bypass the default fadeIn animation for the modal. I took a look at the doc and found these potential props to achieve this:

> animateInConfig
> animationIn
> transitionOptions

Inside my root app file, where I create the stack, I've tried every one of these and in different combinations, but none of them seem to affect the "transition in" animation at all (I may just not know how to use the package correctly). Other options such as disableFlingGesture work as expected.

Expo SDK 50
React Native v0.73.6
NodeJS v18.17.0

(In defaultOptions)

 // No effect
  animateInConfig: {
    duration: 0,
  },
  
   // No effect
  animateInConfig: {
    duration: 5000,
  },
  
  // No effect
    animationIn: (
    animatedValue: Animated.Value,
    toValue: number,
    callback?: () => void
  ) => {
    animatedValue.setValue(toValue); 
    if (callback) callback(); 
  },
  
  // No effect
    transitionOptions: () => {
    return {
      opacity: 1,
    };
  },

**Comment by CharlesMangwa** [comment]
hey @Kaboudouo! i'd be very helpful if you could provide a reproducible demo via [snack](https://snack.expo.dev) pls. it'll make it easier to see if the library isn't been used as expected or if there's an actual bug.

**Comment by CharlesMangwa** [comment]
closing for now as no repro was provided. feel free to reopen whenever you'll have one!
