### ISSUE TITLE
Demo app in expo 

### ISSUE THREAD

**Issue by vamshi9666** [colorfy-software/react-native-modalfy#17]
It would be nice to have a demo app , to test and feel component in real device

**Comment by CharlesMangwa** [comment]
Hi @vamshi9666! There is [a demo app in the repo itself](https://github.com/colorfy-software/react-native-modalfy/tree/master/examples/Simple): you can clone the project and directly run that app on your device 👍

**Comment by vamshi9666** [comment]
Please mention it in readme and docs site.

**Comment by vamshi9666** [comment]
oh.Sorry to miss context. I meant a app in expo, so that it can be accessible from expo-client

**Comment by CharlesMangwa** [comment]
👉 https://colorfy-software.gitbook.io/react-native-modalfy/#try-it-now 👈

Have fun!
