### ISSUE TITLE
createModalStack: 'backdropOpacity: 0' falls back to the default value

### ISSUE THREAD

**Issue by HackedBeat** [colorfy-software/react-native-modalfy#19]
When using 0 for `backdropOpacity`, it falls back to default value.

```js
const stack = createModalStack(modalConfig, {
  backdropOpacity: 0,
});
```

The issue is in this line:
https://github.com/colorfy-software/react-native-modalfy/blob/df2bf5c66efef76a1ba4c3a3b41fcc6cafb8c9f1/lib/ModalStack.tsx#L133
The `||` operator should be changed to `??`.

**Comment by CharlesMangwa** [comment]
Hey @HackedBeat! Thanks for the bug report and the quick fix!
