### ISSUE TITLE
Request: callback on closing modal

### ISSUE THREAD

**Issue by callaars** [colorfy-software/react-native-modalfy#32]
The use case for me is that I'd like to perform a function after closing the modal. However if I start the function while the modal is still disappearing, the experience is a jarred closing animation. It would be nice to have a callback that fires when a modal has closed.

e.g.

`closeModal(afterCloseCallback)`

**Comment by CharlesMangwa** [comment]
Hi @callaars! Your feedback is totally valid and is actually something I've been facing myself. This feature is currently being considered and should hopefully land in the next release, for all the closing methods. We'll update you asap!

**Comment by CharlesMangwa** [comment]
Hey @callaars! Thank you for giving us a bit (a lot) of time to look into this. I'm very happy to let you know that actions callbacks are now supported [in the new Modal v3](https://colorfy-software.gitbook.io/react-native-modalfy/blog/unveiling-modalfy-v3) 🥳 If you're still using Modalfy, I hope this addresses your needs and will help you!

**Comment by callaars** [comment]
Thanks @CharlesMangwa !
