### ISSUE TITLE
Passing params with TypeScript issue

### ISSUE THREAD

**Issue by KestasVenslauskas** [colorfy-software/react-native-modalfy#33]
![download](https://user-images.githubusercontent.com/52245569/95464156-4d2b1680-0982-11eb-9796-f0759aaea2b6.png)

I implemented everything by looking at the docs. TypeScript does not complain at all but the value from `props.testParam` is undefined where value from `props.modal.getParam('testParam')` is expected but TypeScript shows erros.

**Comment by CharlesMangwa** [comment]
Hey @KestasVenslauskas! By the looks of it, you're trying to type a modal component (a modal rendered by Modalfy) but correct me if I'm wrong. If that's the case, you shouldn't be using `ModalProp` as Modalfy exposes a specific interface for modal components: `ModalComponentProp`. You can follow [the related guide in the doc](https://colorfy-software.gitbook.io/react-native-modalfy/guides/typing#modalcomponentprop) that should get you up and running in no time. Feel free to reopen this issue if your problem wasn't fixed!

**Comment by KestasVenslauskas** [comment]
Oh right I had to change `ModalProp `to `ModalComponentProp` then I can reach my params from modal interface
