### ISSUE TITLE
Cannot read property 'openedItems' of undefined

### ISSUE THREAD

**Issue by Dsantosjaime** [colorfy-software/react-native-modalfy#39]
Hi,
I have follow the installation process for modalfy but it crash at runtime and send me this error :

<img width="537" alt="Screenshot 2021-03-04 at 11 23 30" src="https://user-images.githubusercontent.com/9679949/109949865-2d531100-7cdc-11eb-9d07-70c696f638ff.png">

Im my app I currently just have "import {ModalProvider} from 'react-native-modalfy';" in app.js,
and wrap my "<NavigationProvider>" with "<ModalProvider>".
As I don't really have a clue about why this issue is happening I don't know what to bring you about my config or other thing, let me know if I can provide something else that help resolve this problem.

Best regards,

**Comment by CharlesMangwa** [comment]
Hi @Dsantosjaime! Could you provide a reproducible demo on [Expo Snack](https://snack.expo.io) please?

Also, were you able to successfully go through the [Creating a stack](https://colorfy-software.gitbook.io/react-native-modalfy/guides/stack) guide? By the looks of it, my initial assumption is that you didn't provide any stack config to the `ModalProvider` which would explain the error.

**Comment by CharlesMangwa** [comment]
Closing this issue for now due to inactivity, feel free to reopen it if you're still facing that issue!
