### ISSUE TITLE
Closing the current modal while opening other

### ISSUE THREAD

**Issue by syedirfan33** [colorfy-software/react-native-modalfy#4]
I am opening an modal upon pressing a button from another modal and would need to close previously opened modal. 

Please assist. below code doesn't work.

` <Button
            onPress={this.confirmOrder}
            title="CONFIRM"
          />`

`confirmOrder = () => {
    const {
      modal: { openModal, closeModal },
    } = this.props;
    closeModal;
    openModal('NewOrderPost');
  };`

**Comment by CharlesMangwa** [comment]
Hey @syedirfan33! May I ask which version of the library are you using?

**Comment by syedirfan33** [comment]
Hey @CharlesMangwa , I am using  "react-native-modalfy": "^1.0.0-beta.0",

**Comment by CharlesMangwa** [comment]
OK got it. Just to understand your issue a bit better I'd have a few questions:

1. Are the _"previously opened modal"_ and `'NewOrderPost'` using the same component?
2. How many modals do you have in your stack? 
  2.1 If more than 2, was the _"previously opened modal"_ the latest one opened right before you opened `'NewOrderPost'`?

**Comment by syedirfan33** [comment]
1. Yes, I had opened 'NewOrderPre ' before and would need to open 'NewOrderPost' upon clicking 'confirm' button of 'NewOrderPre'

2. I have only these two 2 modals in stack.
const modalConfig = {
  NewOrderPre,
  NewOrderPost,
};

**Comment by CharlesMangwa** [comment]
Gotcha. Could you provide a small reproducible example on [CodeSanbox](https://codesandbox.io) plz? Would make easier for me to help you as best as I can

**Comment by CharlesMangwa** [comment]
Gotcha! So `NewOrderPre` and `NewOrderPost` are using 2 different components under the hood? (could you provide a small reproducible example on [Snack](https://snack.expo.io) plz? Would make it easier to help you as best as I can).

**Comment by syedirfan33** [comment]
Hi @CharlesMangwa , sure. I Will do. NewOrderPost and NewOrderPre  are two differet compoents.

meanwhile Could you please let me know how can I close a modal upon performing some actions?

**Comment by CharlesMangwa** [comment]
Oh my bad @syedirfan33! After reading your initial message again I think I've found where your issue might come from: you wrote `closeModal;` instead of actually calling the function via `closeModal();`, that's why nothing is happening.

**Comment by syedirfan33** [comment]
Omg it's working, thanks a lot!!
