### ISSUE TITLE
Prevent from closing when touched outside

### ISSUE THREAD

**Issue by KestasVenslauskas** [colorfy-software/react-native-modalfy#44]
Can we prevent modal from closing when touch outside happens? For example loading modal?

**Comment by CharlesMangwa** [comment]
Hi @KestasVenslauskas, yes you can do so by defining:

```tsx
modalOptions = {
  backBehavior: 'none', // to disable back button & outside touches
  disableFlingGesture: true, // optionally: to disable fling-to-close gesture
}
```

as explained in the docs: https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions#backbehavior

**Comment by DWboutin** [comment]
Related: https://github.com/colorfy-software/react-native-modalfy/issues/87

Is it possible to have one modal with `backBehavior: 'none'` without creating another stack just for this one?

**Comment by sbaiahmed1** [comment]
> Related: #87
> 
> Is it possible to have one modal with `backBehavior: 'none'` without creating another stack just for this one?

const modalConfig: ModalStackConfig = {
  ShareModal: {
    modal: ShareModal,
    position: 'bottom',
    backBehavior: 'none', // to disable back button & outside touches
    backdropColor: Colors.black,
  },
};
const defaultOptions: ModalOptions = { backdropOpacity: 0.3 };

const stack = createModalStack(modalConfig, defaultOptions);
