### ISSUE TITLE
CloseModals not updating the currentModal value

### ISSUE THREAD

**Issue by jxshco** [colorfy-software/react-native-modalfy#5]
Say if I call openModal a few times e.g.

```
openModal('page1')

openModal('page2')

openModal('page3')
```

then use currentModal to then close the pages

```
closeModals(currentModal) //page 3 closes

closeModals(currentModal) //nothing happens

closeModals(currentModal) //nothing happens
```

This is because currentModal in the state is not being updated when calling closeModals. I've added a temp fix for my use-case at the minute over here: https://github.com/jxshco/react-native-modalfy as an example.

**Comment by CharlesMangwa** [comment]
Hi @jxshco! Thanks for the heads up and sorry for the delay: bug fixed for both `closeModals()` and `closeModal()` (had the same issue there). Please test it in [`react-native-modalfy@1.0.1`](https://www.npmjs.com/package/react-native-modalfy/v/1.0.1) and feel free to re-open this issue if needed!

**Comment by jxshco** [comment]
Works perfectly, thanks @CharlesMangwa
