### ISSUE TITLE
Can I set ModalOptions for each Modal?

### ISSUE THREAD

**Issue by hoanglam10499** [colorfy-software/react-native-modalfy#50]

**Comment by CharlesMangwa** [comment]
Hi @hoanglam10499: as mentioned at the top of the [ModalOptions](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions) documentation, you can do so via [`modalOptions`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modalcomponentwithoptions), either with `static modalOptions = { ... }` if you're inside a class or `AnyFunctionalComponent.modalOptions = { ... }` if you're inside a functional component file.
