### ISSUE TITLE
Close modal in redux

### ISSUE THREAD

**Issue by hieuluis96** [colorfy-software/react-native-modalfy#53]
Hi, I have a loading modal inside redux, but i can't close modal when api has been completed, I like your library and using for my project. This is my code 
```
 function* fetchLoginSaga(action: FetchLoginRequest) {
  try {
    openModal("LoadingModal");
    const response: AxiosResponse = yield call(() => loginRequest(action));
    const result = response.status === 200;
    closeModal("LoadingModal");
    if (result) {

    } else {
      yield put(fetchLoginFailure());
    }
  } catch (e) {
    openModal("ErrorModal");
  }
}
```

**Comment by CharlesMangwa** [comment]
Hi @hieuluis96! Could you please provide a small reproducible demo in [Snack](https://snack.expo.io)? It would make it much easier to debug your issue. Thanks!

**Comment by CharlesMangwa** [comment]
Closing this issue for now, feel free to reopen as soon as you'll have the repro.
