### ISSUE TITLE
TransitionPresets

### ISSUE THREAD

**Issue by teivienn** [colorfy-software/react-native-modalfy#57]
Please add TransitionPresets

for example as in react-navigation
```js
import {
  TransitionPresets,
} from '@react-navigation/stack';
```

```js
import { TransitionPresets } from 'react-native-modalfy'

const ActionSheet = () => ...

ActionSheet.modalOptions = {
   TransitionPresets.ActionSheet,
}

```

**Comment by CharlesMangwa** [comment]
Hi @teivienn! As of now, we're not planning on adding any kind of `TransitionPresets` as we prefer letting you the user do whatever you want there. Feel free to provide a PR and explain your rationale if you feel that's something this library clearly needs.
