### ISSUE TITLE
Override Backdrop component?

### ISSUE THREAD

**Issue by joeyfigaro** [colorfy-software/react-native-modalfy#58]
Is there any way to replace the component used for the Backdrop? I'd like to add support for closing the modal when the backdrop is pressed.

**Comment by CharlesMangwa** [comment]
Hi @joeyfigaro! There's no way to provide your own backdrop, no. That being said, you can already close the modal (or not) by pressing the backdrop as explained [in the docs](https://react-native-modalfy.vercel.app/react-native-modalfy/api/types/modaloptions#backbehavior).
