### ISSUE TITLE
Possible to have a modal stack?  (modal on top of modal)

### ISSUE THREAD

**Issue by sunset1234321** [colorfy-software/react-native-modalfy#60]
I am building a forum, while navigating between comments in a post,  there will be a modal above modal,
can this library achieve it?

**Comment by CharlesMangwa** [comment]
Hi @sunset1234321. As mentioned in the very first section of the [README](https://github.com/colorfy-software/react-native-modalfy#-------react-native-modalfy--):

> 2. Display several modals at once, stack as many as you like.

So the rest will be up to you to figure out. Good luck with your forum! 🍀
