### ISSUE TITLE
Allow a prop to avoid keyboard

### ISSUE THREAD

**Issue by faruuko** [colorfy-software/react-native-modalfy#63]
The current modal does not avoid keyboard. Is there any tip/trick to make that happen?

**Comment by CharlesMangwa** [comment]
Hey @faruuko, the library only renders what you provided to it so it's up to you to implement a `KeyboardAvoidingView` (or any other solution) on your end. We'll reconsider this if we decide to be more opinionated about what Modalfy does.

**Comment by nandha-kumar-hajari** [comment]
@CharlesMangwa still waiting for a fix on this issue. On android it is working fine, but on iOS it is a pain. Please acknowledge
