### ISSUE TITLE
How to subscribe to all modal close events? 

### ISSUE THREAD

**Issue by cmaycumber** [colorfy-software/react-native-modalfy#65]
I'm currently using shallow routing on Next Js with this library on the web. I'd like to track the modal close event so whenever a modal is closed by clicking on the backdrop I can trigger a change in the URL to remove the shallow route that's added when a modal is pushed. 

Is this currently possible? Or should I extend the current modal hook functions to include my custom functionality?

**Comment by CharlesMangwa** [comment]
Hey @cmaycumber! This was not possible up until now indeed. I just published [`v3.1.0`](https://github.com/colorfy-software/react-native-modalfy/releases/tag/v3.1.0) that adds this feature via the existing `addListener` method. The documentation [has been updated](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modalcomponentprop#addlistener) to reflect this, just as the [Expo playground](https://snack.expo.dev/@charles.m/react-native-modalfy) (look at `./components/DemoModal.tsx#L51-53` if you want to quickly check it out).

Let me know if this works for you and addresses your use case!

**Comment by cmaycumber** [comment]
Thanks for adding this!

Still curious, would it be possible to add the onClose listeners to all the modals in the stack without having to declare it across every modal component? 

Something like passing listeners to the `ModalProvider` would run for every modal.

**Comment by CharlesMangwa** [comment]
I would have to think about a way to do so that wouldn't be costly.

In the meantime, if you _absolutely_ need this behavior, you can have all of your modals use a common wrapper component. That way you'd only use `addListener` with `'onClose'` once in that wrapper component and trigger whatever logic you need from there.

**Comment by cmaycumber** [comment]
> I would have to think about a way to do so that wouldn't be costly.

Totally get this. Thanks for the direction.
