### ISSUE TITLE
Is it possible show/hide modals immediately?

### ISSUE THREAD

**Issue by sucrechat** [colorfy-software/react-native-modalfy#79]
https://snack.expo.dev/_LMD_OgPl

First of all, thank you for providing an easy-to-use library.
I wanted modals to show and hide faster than the default setting.
But(perhaps because of the backdrop animation?) the child modals appeared relatively quickly, but the root modal could not reduce the latency.
Even for child modals, it seems that the modal window takes time to close.

**Comment by CharlesMangwa** [comment]
Hey @sucrechat! Thanks for reporting this issue. As of `v3.3.0` that will be released in a few minutes, I added a new [`backdropAnimationDuration`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions#backdropanimationduration) that you can set to `0`. As you correctly guessed, this will address your issue and make the backdrop appear and disappear instantly.
