### ISSUE TITLE
[Android] Gesture events problem cause of FlingGestureHandler

### ISSUE THREAD

**Issue by TommysG** [colorfy-software/react-native-modalfy#86]
First of all, big thank you for this library. Amazing way to avoid boilerplate code and writing once your modal components.

I've experiencing a problem when using a webview inside the modal.
More specifically, i'm using this library [https://github.com/YanYuanFE/react-native-signature-canvas](url) inside the modal. 

In Android the fling gesture is blocking me from drawing in the webview's canvas even if i disable the flingGesture. 
I think the problem is that the fling gesture handler still listening to events, even if it's disabled. 
Somehow on iOs is working fine. I think natively `FlingGestureHandler` has a different implementation (?).

If i remove FlingGestureHandler wrapper from the StackItem, then it's working fine. It has an `enabled` property so maybe it's better using this, to disable fling gesture when `disableFlingGesture = true`.

**Comment by CharlesMangwa** [comment]
Hey @TommysG! Thanks for the report. So did you try setting `enabled: false` in `FlingGestureHandler` inside `StackItem`? Did that work on both platforms? If so, feel free to submit a PR!

**Comment by CharlesMangwa** [comment]
Closing for now due to inactivity, feel free to reopen if needed.
