### ISSUE TITLE
backBehavior "none" only for one Modal

### ISSUE THREAD

**Issue by DWboutin** [colorfy-software/react-native-modalfy#87]
Hi Guys! 

Thanks for this nice lib, very easy and it got smooth animations.

I would love to have mandatory modals, but the `backBehavior` config is set to all Modals that I'll define with `createModalStack(modalConfig, defaultOptions)`.

Is there any way to set this to only one modal?

Thank you

**Comment by CharlesMangwa** [comment]
Hi @DWboutin! Yes, that's possible! As mentioned in [this section](https://colorfy-software.gitbook.io/react-native-modalfy/guides/stack#configuring) of documentation:

> There are 3 ways to provide options to a modal:
> 1. Trough `defaultOptions` in **[`createModalStack()`](https://colorfy-software.gitbook.io/react-native-modalfy/api/createmodalstack)** as we just did
> 2. Inside `modalConfig` by providing a **[`modalOptions`](https://colorfy-software.gitbook.io/react-native-modalfy/api/types/modaloptions)** object instead of just the component directly
> 3. Inside the modal component file itself, via `static modalOptions` (Class) or `MyModalComponent.modalOptions` (Hooks)

So it's up to you to pick up between option 2 and 3 which one you prefer to set `backBehavior` from 👍

**Comment by DWboutin** [comment]
Great! Tyvm
