### ISSUE TITLE
How to test modal components with Jest ?

### ISSUE THREAD

**Issue by GustavoBonfimS** [colorfy-software/react-native-modalfy#99]
I am trying to test my modal components but i don`t know how to mock the  `modal` prop with `closeModal` and `getParam` with Jest and Typescript.

my test code:

```typescript
const modalParams = {
  confirmationType: 'email',
  accessToken: 'test-token',
  userInfo: {
    name: 'John',
  },
};

function mockGetParams(key: string) {
  return modalParams[key];
}

const modalfyMockFunctions = {
  getParam: mockGetParams,
  closeModal: jest.fn(),
};

describe('ConfirmEmailModal', () => {
  it('should render confirmation type correctly', () => {
    render(
      <TestWrapper>
        <ConfirmEmailModal modal={modalfyMockFunctions} />
      </TestWrapper>,
    );
  });
});
```

my modal component:
![image](https://user-images.githubusercontent.com/50304935/222304362-f219c184-3c97-4ea3-a722-f4348b3875ec.png)

The solution was to stop using typing in the component's Props to be able to make a Mock, but this way is not ideal to solve the problem.

**Comment by CharlesMangwa** [comment]
hey @GustavoBonfimS! thanks for your patience with this reply. are you facing any difficulties with this task? 
modalfy doesn't have test covering yet indeed. when it comes to what you were tying to achieve, [here](https://github.com/colorfy-software/react-native-modalfy/blob/main/src/lib/StackItem.tsx#L241-L257) you can see what the `modal` prop each `Modal` receives looks like, hope that will help you with your mock!
